### ISSUE TITLE
Активационная функция

### ISSUE THREAD

**Issue by Miroso02** [gidra5/NN3#4]
Активационную функцию можно хранить внутри NNetwork, ведь на всю нейронку она одна. Также можно создать несколько активационок и дать возможность выбора при создании нейронки.

**Comment by gidra5** [comment]
Я хочу оставить как есть, ибо так можно для каждого нейрона свою активационку поставить, а по поводу разних активационок я специально сделал сеттер, что бы можно было свою поставить на всю нейронку. Такой сеттер не ограничивает выбором из нескольки заранее зделанных активационок
